name: maven

on:
  workflow_call:
    inputs:
      MAVEN_OPTS:
        description: 'Parameters used to start up the JVM running Maven.'
        default: ${{ vars.MAVEN_OPTS }}
        required: false
        type: string
    secrets:
      GPG_PRIVATE_KEY:
        required: false
      GPG_PASSPHRASE:
        required: false
      GIT_USER_EMAIL:
        required: false
      OSS_USERNAME:
        required: false
      OSS_PASSWORD:
        required: false


jobs:
  maven:
    uses: dbstar-org/general/.github/workflows/maven-release.yml@v1
    with:
      MAVEN_OPTS: ${{ inputs.MAVEN_OPTS }}
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
      OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}
